name: Pink Linux CI

on:
  push:
   branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Try building for linux 0
      run: bash ./make.sh
    - name: Try building for linux 1
      run: bash ./make.sh
    - name: Try building for linux 2
      run: bash ./make.sh