name: Pink Windows CI

on:
  push:
   branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Try building for windows 0
      run: cmd /c make.bat
    - name: Try building for windows 1
      run: cmd /c make.bat
    - name: Try building for windows 2
      run: cmd /c make.bat
